name: visualize_data_structures
description: Understand Data Structures with pictorial representations and animations.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  responsive_builder: ^0.1.4
  provider: ^4.0.2
  after_layout: ^1.0.7+2
  font_awesome_flutter: ^8.5.0
  confetti: ^0.3.0
  shared_preferences: ^0.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  fonts:
    - family: Gelasio
      fonts:
        - asset: fonts/gelasio_regular.ttf
    - family: Lato
      fonts:
        - asset: fonts/lato_regular.ttf
    - family: CourierPrime
      fonts:
        - asset: fonts/courierprime_regular.ttf
